#include "RTE_Components.h"
#include  CMSIS_device_header
#include "cmsis_os2.h"
#include "MKL25Z4.h"
#include "system_MKL25Z4.h"

/* RED LEDs */

#define PTE5_RLED1 5
#define PTE4_RLED2 4
#define PTE3_RLED3 3
#define PTE2_RLED4 2
#define PTB11_RLED5 11
#define PTB10_RLED6 10
#define PTB9_RLED7 9
#define PTB8_RLED8 8

#define RLED_MOVING_INTERVAL 500
#define RLED_STOPPED_INTERVAL 250

#define MASK(x) (1 << (x))

void initRLEDGPIO(void){
	// Enable clock to Port B and Port E
	SIM->SCGC5 |= ((SIM_SCGC5_PORTB_MASK) | (SIM_SCGC5_PORTE_MASK)| (SIM_SCGC5_PORTD_MASK));
	
	// Make pins GPIO
	PORTE->PCR[PTE5_RLED1] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[PTE5_RLED1] |= PORT_PCR_MUX(1);
	
	PORTE->PCR[PTE4_RLED2] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[PTE4_RLED2] |= PORT_PCR_MUX(1);
	
	PORTE->PCR[PTE3_RLED3] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[PTE3_RLED3] |= PORT_PCR_MUX(1);
	
	PORTE->PCR[PTE2_RLED4] &= ~PORT_PCR_MUX_MASK;
	PORTE->PCR[PTE2_RLED4] |= PORT_PCR_MUX(1);
	
	PORTB->PCR[PTB11_RLED5] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[PTB11_RLED5] |= PORT_PCR_MUX(1);

	PORTB->PCR[PTB10_RLED6] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[PTB10_RLED6] |= PORT_PCR_MUX(1);
	
	PORTB->PCR[PTB9_RLED7] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[PTB9_RLED7] |= PORT_PCR_MUX(1);
	
	PORTB->PCR[PTB8_RLED8] &= ~PORT_PCR_MUX_MASK;
	PORTB->PCR[PTB8_RLED8] |= PORT_PCR_MUX(1);
	
	// Set pins as output
	PTE->PDDR |= (MASK(PTE5_RLED1) | MASK(PTE4_RLED2) | MASK(PTE3_RLED3) | MASK(PTE2_RLED4));	
	PTB->PDDR |= (MASK(PTB11_RLED5) | MASK(PTB10_RLED6)| MASK(PTB9_RLED7) | MASK(PTB8_RLED8));
}

void offRedLEDs(void){
	PTE->PCOR |= (MASK(PTE5_RLED1) | MASK(PTE4_RLED2) | MASK(PTE3_RLED3) | MASK(PTE2_RLED4));	
	PTB->PCOR |= (MASK(PTB11_RLED5) | MASK(PTB10_RLED6)| MASK(PTB9_RLED7) | MASK(PTB8_RLED8));
}

void onRedLEDs(void){
	PTE->PSOR |= (MASK(PTE5_RLED1) | MASK(PTE4_RLED2) | MASK(PTE3_RLED3) | MASK(PTE2_RLED4));	
	PTB->PSOR |= (MASK(PTB11_RLED5) | MASK(PTB10_RLED6)| MASK(PTB9_RLED7) | MASK(PTB8_RLED8));
}

void flashRedLEDs(int interval) {
		onRedLEDs();
		osDelay(interval);
		offRedLEDs();
		osDelay(interval);
}
